name: CI untuk Aplikasi Restoran

on:
  push:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout kode
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Cek Error di Semua File PHP
      run: |
        find . -name "*.php" -exec php -l {} \;
